---
deployment:
  tasks:
    - export DEPLOY_PATH=/home/aspireso/public_html/dev-test.aspire-solution.com
    - rm -rf $DEPLOY_PATH/*
    - npm ci
    - npm run build
    - npm run export
    - cp -R out/* $DEPLOY_PATH/
