---
deployment:
  tasks:
    - export DEPLOYPATH=/home/aspireso/dev-test.aspire-solution.com/
    - /bin/npm install
    - /bin/npm run build
    - /bin/npm run export
    - /bin/cp -R out/* $DEPLOYPATH
